2013/09/20 17:39:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "gii".' in D:\cloud\cloudy\yii\framework\web\CController.php:483
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\CController.php(270): CController->missingAction('gii')
#1 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(282): CController->run('gii')
#2 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('site/gii')
#3 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\cloud\cloudy\index.php(13): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=site/gii
---
2013/09/20 17:39:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gii".' in D:\cloud\cloudy\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gii')
#1 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\cloud\cloudy\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=gii
---
2013/09/21 14:27:42 [error] [php] Attempt to assign property of non-object (D:\cloud\cloudy\yii\framework\db\ar\CActiveRecord.php:1349)
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#1 D:\cloud\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#2 D:\cloud\cloudy\yii\framework\web\CController.php(286): SiteController->runAction()
#3 D:\cloud\cloudy\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#4 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(282): SiteController->run()
#5 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#6 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#7 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\models\Menu.php (104)
in D:\cloud\cloudy\protected\controllers\SiteController.php (36)
in D:\cloud\cloudy\index.php (13)
2013/09/21 15:28:34 [error] [php] Undefined variable: container (D:\cloud\cloudy\protected\views\layouts\main.php:360)
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#1 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#2 D:\cloud\cloudy\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#3 D:\cloud\cloudy\yii\framework\web\CBaseController.php(206): CContentDecorator->run()
#4 D:\cloud\cloudy\yii\framework\web\CBaseController.php(300): SiteController->endWidget()
#5 D:\cloud\cloudy\protected\views\layouts\column1.php(6): SiteController->endContent()
#6 D:\cloud\cloudy\yii\framework\web\CBaseController.php(126): require()
#7 D:\cloud\cloudy\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 D:\cloud\cloudy\yii\framework\web\CController.php(784): SiteController->renderFile()
#9 D:\cloud\cloudy\protected\controllers\SiteController.php(37): SiteController->render()
#10 D:\cloud\cloudy\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\cloud\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 D:\cloud\cloudy\yii\framework\web\CController.php(286): SiteController->runAction()
#13 D:\cloud\cloudy\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#14 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(282): SiteController->run()
#15 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\views\layouts\main.php (360)
in D:\cloud\cloudy\protected\views\layouts\column1.php (6)
in D:\cloud\cloudy\protected\controllers\SiteController.php (37)
2013/09/21 16:09:14 [error] [php] Undefined variable: menu (D:\cloud\cloudy\protected\views\layouts\main.php:159)
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#1 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#2 D:\cloud\cloudy\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#3 D:\cloud\cloudy\yii\framework\web\CBaseController.php(206): CContentDecorator->run()
#4 D:\cloud\cloudy\yii\framework\web\CBaseController.php(300): SiteController->endWidget()
#5 D:\cloud\cloudy\protected\views\layouts\column1.php(6): SiteController->endContent()
#6 D:\cloud\cloudy\yii\framework\web\CBaseController.php(126): require()
#7 D:\cloud\cloudy\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 D:\cloud\cloudy\yii\framework\web\CController.php(784): SiteController->renderFile()
#9 D:\cloud\cloudy\protected\controllers\SiteController.php(37): SiteController->render()
#10 D:\cloud\cloudy\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\cloud\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 D:\cloud\cloudy\yii\framework\web\CController.php(286): SiteController->runAction()
#13 D:\cloud\cloudy\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#14 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(282): SiteController->run()
#15 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\views\layouts\main.php (159)
in D:\cloud\cloudy\protected\views\layouts\column1.php (6)
in D:\cloud\cloudy\protected\controllers\SiteController.php (37)
2013/09/21 16:19:01 [error] [php] Undefined variable: menu (D:\cloud\cloudy\protected\views\layouts\main.php:159)
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#1 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#2 D:\cloud\cloudy\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#3 D:\cloud\cloudy\yii\framework\web\CBaseController.php(206): CContentDecorator->run()
#4 D:\cloud\cloudy\yii\framework\web\CBaseController.php(300): SiteController->endWidget()
#5 D:\cloud\cloudy\protected\views\layouts\column1.php(6): SiteController->endContent()
#6 D:\cloud\cloudy\yii\framework\web\CBaseController.php(126): require()
#7 D:\cloud\cloudy\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 D:\cloud\cloudy\yii\framework\web\CController.php(784): SiteController->renderFile()
#9 D:\cloud\cloudy\protected\controllers\SiteController.php(37): SiteController->render()
#10 D:\cloud\cloudy\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\cloud\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 D:\cloud\cloudy\yii\framework\web\CController.php(286): SiteController->runAction()
#13 D:\cloud\cloudy\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#14 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(282): SiteController->run()
#15 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\views\layouts\main.php (159)
in D:\cloud\cloudy\protected\views\layouts\column1.php (6)
in D:\cloud\cloudy\protected\controllers\SiteController.php (37)
2013/09/21 16:19:02 [error] [php] Undefined variable: menu (D:\cloud\cloudy\protected\views\layouts\main.php:159)
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#1 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#2 D:\cloud\cloudy\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#3 D:\cloud\cloudy\yii\framework\web\CBaseController.php(206): CContentDecorator->run()
#4 D:\cloud\cloudy\yii\framework\web\CBaseController.php(300): SiteController->endWidget()
#5 D:\cloud\cloudy\protected\views\layouts\column1.php(6): SiteController->endContent()
#6 D:\cloud\cloudy\yii\framework\web\CBaseController.php(126): require()
#7 D:\cloud\cloudy\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 D:\cloud\cloudy\yii\framework\web\CController.php(784): SiteController->renderFile()
#9 D:\cloud\cloudy\protected\controllers\SiteController.php(37): SiteController->render()
#10 D:\cloud\cloudy\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\cloud\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 D:\cloud\cloudy\yii\framework\web\CController.php(286): SiteController->runAction()
#13 D:\cloud\cloudy\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#14 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(282): SiteController->run()
#15 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\views\layouts\main.php (159)
in D:\cloud\cloudy\protected\views\layouts\column1.php (6)
in D:\cloud\cloudy\protected\controllers\SiteController.php (37)
2013/09/21 16:36:09 [error] [php] Undefined variable: subMenu (D:\cloud\cloudy\protected\views\layouts\main.php:157)
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(76): SiteController->renderFile()
#1 D:\cloud\cloudy\yii\framework\web\widgets\CContentDecorator.php(54): CContentDecorator->decorate()
#2 D:\cloud\cloudy\yii\framework\web\widgets\COutputProcessor.php(44): CContentDecorator->processOutput()
#3 D:\cloud\cloudy\yii\framework\web\CBaseController.php(206): CContentDecorator->run()
#4 D:\cloud\cloudy\yii\framework\web\CBaseController.php(300): SiteController->endWidget()
#5 D:\cloud\cloudy\protected\views\layouts\column1.php(6): SiteController->endContent()
#6 D:\cloud\cloudy\yii\framework\web\CBaseController.php(126): require()
#7 D:\cloud\cloudy\yii\framework\web\CBaseController.php(95): SiteController->renderInternal()
#8 D:\cloud\cloudy\yii\framework\web\CController.php(784): SiteController->renderFile()
#9 D:\cloud\cloudy\protected\controllers\SiteController.php(37): SiteController->render()
#10 D:\cloud\cloudy\yii\framework\web\actions\CInlineAction.php(49): SiteController->actionIndex()
#11 D:\cloud\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#12 D:\cloud\cloudy\yii\framework\web\CController.php(286): SiteController->runAction()
#13 D:\cloud\cloudy\yii\framework\web\CController.php(265): SiteController->runActionWithFilters()
#14 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(282): SiteController->run()
#15 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#16 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#17 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\views\layouts\main.php (157)
in D:\cloud\cloudy\protected\views\layouts\column1.php (6)
in D:\cloud\cloudy\protected\controllers\SiteController.php (37)
2013/09/21 16:40:24 [error] [php] Declaration of Controller::beforeAction() should be compatible with that of CController::beforeAction() (D:\cloud\cloudy\protected\components\Controller.php:7)
Stack trace:
#0 D:\cloud\cloudy\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(354): require()
#2 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\components\Controller.php (7)
in D:\cloud\cloudy\protected\controllers\SiteController.php (4)
in D:\cloud\cloudy\index.php (13)
2013/09/21 16:48:09 [error] [php] Declaration of Controller::beforeAction() should be compatible with that of CController::beforeAction() (D:\cloud\cloudy\protected\components\Controller.php:7)
Stack trace:
#0 D:\cloud\cloudy\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(354): require()
#2 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\components\Controller.php (7)
in D:\cloud\cloudy\protected\controllers\SiteController.php (4)
in D:\cloud\cloudy\index.php (13)
2013/09/21 16:52:43 [error] [php] Declaration of Controller::beforeAction() should be compatible with that of CController::beforeAction() (D:\cloud\cloudy\protected\components\Controller.php:7)
Stack trace:
#0 D:\cloud\cloudy\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(354): require()
#2 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\components\Controller.php (7)
in D:\cloud\cloudy\protected\controllers\SiteController.php (4)
in D:\cloud\cloudy\index.php (13)
2013/09/21 16:52:44 [error] [php] Declaration of Controller::beforeAction() should be compatible with that of CController::beforeAction() (D:\cloud\cloudy\protected\components\Controller.php:7)
Stack trace:
#0 D:\cloud\cloudy\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(354): require()
#2 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\components\Controller.php (7)
in D:\cloud\cloudy\protected\controllers\SiteController.php (4)
in D:\cloud\cloudy\index.php (13)
2013/09/21 17:15:19 [error] [php] Declaration of Controller::beforeAction() should be compatible with that of CController::beforeAction() (D:\cloud\cloudy\protected\components\Controller.php:7)
Stack trace:
#0 D:\cloud\cloudy\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(354): require()
#2 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\components\Controller.php (7)
in D:\cloud\cloudy\protected\controllers\SiteController.php (4)
in D:\cloud\cloudy\index.php (13)
2013/09/21 17:15:58 [error] [php] Declaration of Controller::beforeAction() should be compatible with that of CController::beforeAction() (D:\cloud\cloudy\protected\components\Controller.php:7)
Stack trace:
#0 D:\cloud\cloudy\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(354): require()
#2 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\components\Controller.php (7)
in D:\cloud\cloudy\protected\controllers\SiteController.php (4)
in D:\cloud\cloudy\index.php (13)
2013/09/21 17:15:59 [error] [php] Declaration of Controller::beforeAction() should be compatible with that of CController::beforeAction() (D:\cloud\cloudy\protected\components\Controller.php:7)
Stack trace:
#0 D:\cloud\cloudy\protected\controllers\SiteController.php(4): spl_autoload_call()
#1 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(354): require()
#2 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(276): CWebApplication->createController()
#3 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#4 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=site/index
in D:\cloud\cloudy\protected\components\Controller.php (7)
in D:\cloud\cloudy\protected\controllers\SiteController.php (4)
in D:\cloud\cloudy\index.php (13)
2013/09/30 22:51:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "gallery".' in D:\cloud\cloudy\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('gallery')
#1 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\cloud\cloudy\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/?r=gallery
---
2013/10/07 00:36:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "blog".' in D:\cloud\cloudy\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('blog')
#1 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\cloud\cloudy\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/?r=blog
HTTP_REFERER=http://cloud.test/?r=gallery
---
2013/10/12 14:02:21 [error] [php] Trying to get property of non-object (D:\cloud\cloudy\protected\views\gallery\index.php:25)
Stack trace:
#0 D:\cloud\cloudy\yii\framework\web\CController.php(869): GalleryController->renderFile()
#1 D:\cloud\cloudy\yii\framework\web\CController.php(782): GalleryController->renderPartial()
#2 D:\cloud\cloudy\protected\controllers\GalleryController.php(26): GalleryController->render()
#3 D:\cloud\cloudy\yii\framework\web\actions\CInlineAction.php(49): GalleryController->actionIndex()
#4 D:\cloud\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#5 D:\cloud\cloudy\yii\framework\web\CController.php(286): GalleryController->runAction()
#6 D:\cloud\cloudy\yii\framework\web\CController.php(265): GalleryController->runActionWithFilters()
#7 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(282): GalleryController->run()
#8 D:\cloud\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#9 D:\cloud\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#10 D:\cloud\cloudy\index.php(13): CWebApplication->run()
REQUEST_URI=/index.php?r=gallery
in D:\cloud\cloudy\protected\views\gallery\index.php (25)
in D:\cloud\cloudy\protected\controllers\GalleryController.php (26)
in D:\cloud\cloudy\index.php (13)
2013/10/20 03:22:43 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'cloudy'' in D:\cloudy\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\cloudy\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\cloudy\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\cloudy\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\cloudy\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\cloudy\protected\components\Controller.php(31): CActiveRecord->__construct()
#9 D:\cloudy\yii\framework\web\CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 D:\cloudy\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 D:\cloudy\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\cloudy\yii\framework\web\CWebApplication.php(282): CController->run('')
#13 D:\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#14 D:\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\cloudy\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/10/30 15:22:32 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'cloudy'' in D:\cloudy\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\cloudy\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\cloudy\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\cloudy\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\cloudy\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\cloudy\protected\components\Controller.php(31): CActiveRecord->__construct()
#9 D:\cloudy\yii\framework\web\CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 D:\cloudy\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 D:\cloudy\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\cloudy\yii\framework\web\CWebApplication.php(282): CController->run('')
#13 D:\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#14 D:\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\cloudy\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/11/02 08:23:48 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'cloudy'' in D:\cloudy\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\cloudy\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\cloudy\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\cloudy\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\cloudy\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\cloudy\protected\components\Controller.php(31): CActiveRecord->__construct()
#9 D:\cloudy\yii\framework\web\CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 D:\cloudy\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 D:\cloudy\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\cloudy\yii\framework\web\CWebApplication.php(282): CController->run('')
#13 D:\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#14 D:\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\cloudy\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/11/02 08:27:35 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1049] Unknown database 'cloudy'' in D:\cloudy\yii\framework\db\CDbConnection.php:382
Stack trace:
#0 D:\cloudy\yii\framework\db\CDbConnection.php(330): CDbConnection->open()
#1 D:\cloudy\yii\framework\db\CDbConnection.php(308): CDbConnection->setActive(true)
#2 D:\cloudy\yii\framework\base\CModule.php(387): CDbConnection->init()
#3 D:\cloudy\yii\framework\base\CApplication.php(450): CModule->getComponent('db')
#4 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(634): CApplication->getDb()
#5 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 D:\cloudy\yii\framework\db\ar\CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 D:\cloudy\protected\components\Controller.php(31): CActiveRecord->__construct()
#9 D:\cloudy\yii\framework\web\CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 D:\cloudy\yii\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#11 D:\cloudy\yii\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 D:\cloudy\yii\framework\web\CWebApplication.php(282): CController->run('')
#13 D:\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('')
#14 D:\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#15 D:\cloudy\index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:31:10 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:31:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:31:15 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:33:21 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:33:22 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:34:05 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:34:06 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:34:08 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:34:09 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:34:11 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:34:12 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:37:38 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:37:40 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '192.168.1.135' (111)' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:38:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host 'cloud.blog' is not allowed to connect to this MySQL server' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:38:33 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host 'cloud.blog' is not allowed to connect to this MySQL server' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:38:34 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host 'cloud.blog' is not allowed to connect to this MySQL server' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:38:46 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host 'cloud.blog' is not allowed to connect to this MySQL server' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:38:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host 'cloud.blog' is not allowed to connect to this MySQL server' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/09 17:38:47 [error] [exception.CDbException] exception 'CDbException' with message 'CDbConnection failed to open the DB connection: SQLSTATE[HY000] [1130] Host 'cloud.blog' is not allowed to connect to this MySQL server' in /var/www/cloudy/yii/framework/db/CDbConnection.php:382
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbConnection.php(330): CDbConnection->open()
#1 /var/www/cloudy/yii/framework/db/CDbConnection.php(308): CDbConnection->setActive(true)
#2 /var/www/cloudy/yii/framework/base/CModule.php(387): CDbConnection->init()
#3 /var/www/cloudy/yii/framework/base/CApplication.php(450): CModule->getComponent('db')
#4 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(634): CApplication->getDb()
#5 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(2361): CActiveRecord->getDbConnection()
#6 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(411): CActiveRecordMetaData->__construct(Object(Menu))
#7 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(79): CActiveRecord->getMetaData()
#8 /var/www/cloudy/protected/components/Controller.php(31): CActiveRecord->__construct()
#9 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#11 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#13 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#14 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#15 /var/www/cloudy/index.php(13): CApplication->run()
#16 {main}
REQUEST_URI=/
---
2013/12/11 16:51:10 [error] [exception.Exception] exception 'Exception' with message 'load error: failed to find /var/www/cloudy/protected/assets/less/index.less' in /var/www/cloudy/protected/components/less/lessc.inc.php:1818
Stack trace:
#0 /var/www/cloudy/protected/components/less/lessc.inc.php(1844): lessc->compileFile('/var/www/cloudy...', '/var/www/cloudy...')
#1 /var/www/cloudy/protected/components/Controller.php(44): lessc->checkedCompile('/var/www/cloudy...', '/var/www/cloudy...')
#2 /var/www/cloudy/protected/components/Controller.php(33): Controller->compileLess()
#3 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/
---
2013/12/11 16:51:11 [error] [exception.Exception] exception 'Exception' with message 'load error: failed to find /var/www/cloudy/protected/assets/less/index.less' in /var/www/cloudy/protected/components/less/lessc.inc.php:1818
Stack trace:
#0 /var/www/cloudy/protected/components/less/lessc.inc.php(1844): lessc->compileFile('/var/www/cloudy...', '/var/www/cloudy...')
#1 /var/www/cloudy/protected/components/Controller.php(44): lessc->checkedCompile('/var/www/cloudy...', '/var/www/cloudy...')
#2 /var/www/cloudy/protected/components/Controller.php(33): Controller->compileLess()
#3 /var/www/cloudy/yii/framework/web/CController.php(306): Controller->beforeAction(Object(CInlineAction))
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/
---
2013/12/11 18:50:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oldIndex".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('oldIndex')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=oldIndex
---
2013/12/11 18:50:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "oldIndex".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('oldIndex')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=oldIndex
---
2013/12/11 18:51:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "index".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('index')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=index
---
2013/12/12 13:56:19 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/cloudy/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/cloudy/index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/?r=gii
---
2013/12/12 13:56:27 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/cloudy/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/cloudy/index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/?r=gii
---
2013/12/12 13:56:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/cloudy/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/cloudy/index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/?r=gii
---
2013/12/12 14:32:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/?r=test/pdf
---
2013/12/12 14:33:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf2Image".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/?r=test/pdf2Image
---
2013/12/12 14:34:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf2Image".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:36:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf2Image".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:40:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf2Image".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:40:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf2Image".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:40:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf2Image".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:40:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf2Image".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:40:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf2Image".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:40:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/pdf2Image".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:40:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "test/index".' in /var/www/cloudy/yii/framework/web/CWebApplication.php:286
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/index')
#1 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#2 /var/www/cloudy/index.php(15): CApplication->run()
#3 {main}
REQUEST_URI=/index.php?r=test/index
---
2013/12/12 14:41:07 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "index".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(21): CController->render('index', Array)
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionIndex()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('index')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/index')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/index
---
2013/12/12 14:41:15 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "pdf".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('pdf', Array, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(32): CController->render('pdf', Array)
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionPdf2Image()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('pdf2Image')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:47:02 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "pdf".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('pdf', Array, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(22): CController->render('pdf', Array)
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionPdf2Image()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('pdf2Image')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:47:03 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "pdf".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('pdf', Array, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(22): CController->render('pdf', Array)
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionPdf2Image()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('pdf2Image')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:47:03 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "pdf".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('pdf', Array, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(22): CController->render('pdf', Array)
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionPdf2Image()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('pdf2Image')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:47:03 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "pdf".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('pdf', Array, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(22): CController->render('pdf', Array)
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionPdf2Image()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('pdf2Image')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:47:04 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "pdf".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('pdf', Array, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(22): CController->render('pdf', Array)
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionPdf2Image()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('pdf2Image')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:47:04 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "pdf".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('pdf', Array, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(22): CController->render('pdf', Array)
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionPdf2Image()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('pdf2Image')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/pdf2Image')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/pdf2Image
---
2013/12/12 14:47:25 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "index".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(11): CController->render('index', Array)
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionIndex()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('index')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/index')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/index
---
2013/12/12 14:48:31 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "index".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('index', NULL, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(9): CController->render('index')
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionIndex()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('index')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/index')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/index
---
2013/12/12 14:48:32 [error] [exception.CException] exception 'CException' with message 'TestController cannot find the requested view "index".' in /var/www/cloudy/yii/framework/web/CController.php:878
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('index', NULL, true)
#1 /var/www/cloudy/protected/controllers/TestController.php(9): CController->render('index')
#2 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): TestController->actionIndex()
#3 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#4 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#5 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('index')
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('test/index')
#8 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#9 /var/www/cloudy/index.php(15): CApplication->run()
#10 {main}
REQUEST_URI=/index.php?r=test/index
---
2013/12/12 16:40:34 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/cloudy/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/cloudy/index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=gii
---
2013/12/12 16:46:36 [error] [exception.CHttpException.403] exception 'CHttpException' with message 'You are not allowed to access this page.' in /var/www/cloudy/yii/framework/gii/GiiModule.php:170
Stack trace:
#0 /var/www/cloudy/yii/framework/web/CController.php(263): GiiModule->beforeControllerAction(Object(DefaultController), Object(CInlineAction))
#1 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#2 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('gii')
#3 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#4 /var/www/cloudy/index.php(15): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=gii
---
2013/12/12 17:42:03 [error] [exception.CException] exception 'CException' with message 'Property "WpPosts.image_url" is not defined.' in /var/www/cloudy/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('image_url')
#1 /var/www/cloudy/protected/views/site/index.php(29): CActiveRecord->__get('image_url')
#2 /var/www/cloudy/yii/framework/web/CBaseController.php(126): require('/var/www/cloudy...')
#3 /var/www/cloudy/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/cloudy...', Array, true)
#4 /var/www/cloudy/yii/framework/web/CController.php(869): CBaseController->renderFile('/var/www/cloudy...', Array, true)
#5 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#6 /var/www/cloudy/protected/controllers/SiteController.php(42): CController->render('index', Array)
#7 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#8 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#13 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/cloudy/index.php(17): CApplication->run()
#15 {main}
REQUEST_URI=/
---
2013/12/12 17:43:59 [error] [exception.CException] exception 'CException' with message 'Property "WpPosts.image_url" is not defined.' in /var/www/cloudy/yii/framework/base/CComponent.php:130
Stack trace:
#0 /var/www/cloudy/yii/framework/db/ar/CActiveRecord.php(145): CComponent->__get('image_url')
#1 /var/www/cloudy/protected/views/site/index.php(29): CActiveRecord->__get('image_url')
#2 /var/www/cloudy/yii/framework/web/CBaseController.php(126): require('/var/www/cloudy...')
#3 /var/www/cloudy/yii/framework/web/CBaseController.php(95): CBaseController->renderInternal('/var/www/cloudy...', Array, true)
#4 /var/www/cloudy/yii/framework/web/CController.php(869): CBaseController->renderFile('/var/www/cloudy...', Array, true)
#5 /var/www/cloudy/yii/framework/web/CController.php(782): CController->renderPartial('index', Array, true)
#6 /var/www/cloudy/protected/controllers/SiteController.php(42): CController->render('index', Array)
#7 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#8 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#9 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#10 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#11 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#12 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#13 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#14 /var/www/cloudy/index.php(17): CApplication->run()
#15 {main}
REQUEST_URI=/
---
2013/12/12 18:03:01 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty. The SQL statement executed was: .
in /var/www/cloudy/protected/models/WpPosts.php (179)
in /var/www/cloudy/protected/controllers/SiteController.php (36)
in /var/www/cloudy/index.php (17)
2013/12/12 18:03:01 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty. The SQL statement executed was: ' in /var/www/cloudy/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /var/www/cloudy/protected/models/WpPosts.php(179): CDbCommand->queryAll()
#2 /var/www/cloudy/protected/controllers/SiteController.php(36): WpPosts->getPosts()
#3 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#4 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#6 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#8 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#9 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /var/www/cloudy/index.php(17): CApplication->run()
#11 {main}
REQUEST_URI=/
---
2013/12/12 18:05:04 [error] [system.db.CDbCommand] CDbCommand::fetchAll() failed: SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty. The SQL statement executed was: .
in /var/www/cloudy/protected/models/WpPosts.php (179)
in /var/www/cloudy/protected/controllers/SiteController.php (36)
in /var/www/cloudy/index.php (17)
2013/12/12 18:05:04 [error] [exception.CDbException] exception 'CDbException' with message 'CDbCommand failed to execute the SQL statement: SQLSTATE[42000]: Syntax error or access violation: 1065 Query was empty. The SQL statement executed was: ' in /var/www/cloudy/yii/framework/db/CDbCommand.php:543
Stack trace:
#0 /var/www/cloudy/yii/framework/db/CDbCommand.php(396): CDbCommand->queryInternal('fetchAll', Array, Array)
#1 /var/www/cloudy/protected/models/WpPosts.php(179): CDbCommand->queryAll()
#2 /var/www/cloudy/protected/controllers/SiteController.php(36): WpPosts->getPosts()
#3 /var/www/cloudy/yii/framework/web/actions/CInlineAction.php(49): SiteController->actionIndex()
#4 /var/www/cloudy/yii/framework/web/CController.php(308): CInlineAction->runWithParams(Array)
#5 /var/www/cloudy/yii/framework/web/CController.php(286): CController->runAction(Object(CInlineAction))
#6 /var/www/cloudy/yii/framework/web/CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#7 /var/www/cloudy/yii/framework/web/CWebApplication.php(282): CController->run('')
#8 /var/www/cloudy/yii/framework/web/CWebApplication.php(141): CWebApplication->runController('')
#9 /var/www/cloudy/yii/framework/base/CApplication.php(180): CWebApplication->processRequest()
#10 /var/www/cloudy/index.php(17): CApplication->run()
#11 {main}
REQUEST_URI=/
---
2013/12/21 10:12:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "getLuckyDog".' in D:\git\cloudy\yii\framework\web\CController.php:483
Stack trace:
#0 D:\git\cloudy\yii\framework\web\CController.php(270): CController->missingAction('getLuckyDog')
#1 D:\git\cloudy\yii\framework\web\CWebApplication.php(282): CController->run('getLuckyDog')
#2 D:\git\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('lottery/getLuck...')
#3 D:\git\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\git\cloudy\index.php(27): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=lottery/getLuckyDog&lala=&gaga=
HTTP_REFERER=http://cloud.blog/index.php?r=lottery
---
2013/12/21 10:13:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "actionGetLuckyDog".' in D:\git\cloudy\yii\framework\web\CController.php:483
Stack trace:
#0 D:\git\cloudy\yii\framework\web\CController.php(270): CController->missingAction('actionGetLuckyD...')
#1 D:\git\cloudy\yii\framework\web\CWebApplication.php(282): CController->run('actionGetLuckyD...')
#2 D:\git\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('lottery/actionG...')
#3 D:\git\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\git\cloudy\index.php(27): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=lottery/actionGetLuckyDog&lala=&gaga=
HTTP_REFERER=http://cloud.blog/index.php?r=lottery
---
2013/12/21 10:13:35 [error] [php] rand() expects parameter 2 to be long, string given (D:\git\cloudy\protected\controllers\LotteryController.php:28)
Stack trace:
#0 D:\git\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\git\cloudy\yii\framework\web\CController.php(286): LotteryController->runAction()
#2 D:\git\cloudy\yii\framework\web\CController.php(265): LotteryController->runActionWithFilters()
#3 D:\git\cloudy\yii\framework\web\CWebApplication.php(282): LotteryController->run()
#4 D:\git\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\git\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\git\cloudy\index.php(27): CWebApplication->run()
REQUEST_URI=/index.php?r=lottery/getLuckyDog&lala=&gaga=
in D:\git\cloudy\protected\controllers\LotteryController.php (28)
in D:\git\cloudy\index.php (27)
2013/12/21 10:14:01 [error] [php] rand() expects parameter 2 to be long, string given (D:\git\cloudy\protected\controllers\LotteryController.php:28)
Stack trace:
#0 D:\git\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\git\cloudy\yii\framework\web\CController.php(286): LotteryController->runAction()
#2 D:\git\cloudy\yii\framework\web\CController.php(265): LotteryController->runActionWithFilters()
#3 D:\git\cloudy\yii\framework\web\CWebApplication.php(282): LotteryController->run()
#4 D:\git\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\git\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\git\cloudy\index.php(27): CWebApplication->run()
REQUEST_URI=/index.php?r=lottery/getLuckyDog
in D:\git\cloudy\protected\controllers\LotteryController.php (28)
in D:\git\cloudy\index.php (27)
2013/12/21 10:14:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "actionGetLuckyDog".' in D:\git\cloudy\yii\framework\web\CController.php:483
Stack trace:
#0 D:\git\cloudy\yii\framework\web\CController.php(270): CController->missingAction('actionGetLuckyD...')
#1 D:\git\cloudy\yii\framework\web\CWebApplication.php(282): CController->run('actionGetLuckyD...')
#2 D:\git\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('lottery/actionG...')
#3 D:\git\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#4 D:\git\cloudy\index.php(27): CApplication->run()
#5 {main}
REQUEST_URI=/index.php?r=lottery/actionGetLuckyDog
---
2013/12/21 10:14:55 [error] [php] rand() expects parameter 2 to be long, string given (D:\git\cloudy\protected\controllers\LotteryController.php:28)
Stack trace:
#0 D:\git\cloudy\yii\framework\web\CController.php(308): CInlineAction->runWithParams()
#1 D:\git\cloudy\yii\framework\web\CController.php(286): LotteryController->runAction()
#2 D:\git\cloudy\yii\framework\web\CController.php(265): LotteryController->runActionWithFilters()
#3 D:\git\cloudy\yii\framework\web\CWebApplication.php(282): LotteryController->run()
#4 D:\git\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController()
#5 D:\git\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#6 D:\git\cloudy\index.php(27): CWebApplication->run()
REQUEST_URI=/index.php?r=lottery/getLuckyDog
in D:\git\cloudy\protected\controllers\LotteryController.php (28)
in D:\git\cloudy\index.php (27)
2014/02/09 06:22:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "swipeJs".' in D:\git\cloudy\yii\framework\web\CWebApplication.php:286
Stack trace:
#0 D:\git\cloudy\yii\framework\web\CWebApplication.php(141): CWebApplication->runController('swipeJs')
#1 D:\git\cloudy\yii\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\git\cloudy\index.php(27): CApplication->run()
#3 {main}
REQUEST_URI=/?r=swipeJs
---
